import assert from 'node:assert/strict';
import { validateGenerationSubmission, validateImageSize, generationRecipe, toImagesPayload } from '../shared/generation-contract.mjs';
import { buildSeriesSplitPrompt, parseSeriesPlan, scenePrompt, SERIES_PRESETS } from '../shared/series-planning.mjs';
import { validateSubmissionImages } from '../server/generation-input.mjs';
import { imageInfo, normalizeImageResult } from '../server/image-result.mjs';
import { submissionHash } from '../server/state-store.mjs';
import { PNG, PNG_URL, MASK_URL, submission } from './fixtures.mjs';

const input = validateGenerationSubmission(submission('contract'));
assert.equal(toImagesPayload(input).n, 1);
assert.equal(toImagesPayload(input).quality, 'medium');
assert.equal(toImagesPayload(input).output_format, 'png');
assert.equal(Object.hasOwn(toImagesPayload(input), 'output_compression'), false);
for (const key of ['seed', 'cfg', 'cfg_scale', 'steps', 'num_inference_steps', 'weight', 'image_strength', 'reference_image_weight']) assert.throws(() => validateGenerationSubmission(submission(`invalid-${key}`, { [key]: 1 })), /不支持的字段/);
for (const size of ['1024x1024', '1280x720', '720x1280', '1024x768', '768x1024', '1536x1024', '1024x1536', '1344x576', '3840x2160', '2880x2880', 'auto']) assert.equal(validateImageSize(size), size);
for (const size of ['1x1', '1254x1254', '4096x4096', '1024x4000', 'wide']) assert.throws(() => validateImageSize(size));
assert.throws(() => validateGenerationSubmission(submission('bad-format', { outputFormat: 'jpeg', background: 'transparent' })), /透明背景/);
assert.throws(() => validateGenerationSubmission(submission('bad-quality', { quality: 'ultra' })), /质量/);
assert.throws(() => validateGenerationSubmission(submission('bad-mask', { mask: MASK_URL })), /需要参考图/);
assert.throws(() => validateGenerationSubmission(submission('refs', { references: Array(5).fill({ id: 'ref', name: 'ref', dataUrl: PNG_URL }) })), /最多/);
const edit = validateGenerationSubmission(submission('edit', { references: [{ id: 'ref', name: 'ref.png', dataUrl: PNG_URL }], mask: MASK_URL }));
validateSubmissionImages(edit);
assert.equal(edit.clientContext.mode, 'edit');
assert.equal(generationRecipe(edit).hasMask, true);
assert.equal(JSON.stringify(generationRecipe(edit)).includes('base64'), false);
assert.deepEqual(imageInfo(PNG), { mime_type: 'image/png', width: 2, height: 2 });
assert.throws(() => validateSubmissionImages(submission('bad-image', { references: [{ id: 'ref', name: 'ref.png', dataUrl: 'data:image/png;base64,ZmFrZQ==' }] })), /损坏/);
assert.throws(() => validateSubmissionImages(submission('bad-mime', { references: [{ id: 'ref', name: 'ref.jpg', dataUrl: PNG_URL.replace('image/png', 'image/jpeg') }] })), /内容不一致/);
assert.equal(submissionHash(input), submissionHash({ ...input, referenceImage: { id: 'ref', name: 'ref.png', dataUrl: PNG_URL } }));
const malformed = await normalizeImageResult({ ok: true, body: Buffer.from(JSON.stringify({ data: [{ b64_json: 'YmFk' }] })) });
assert.equal(malformed.ok, false);
assert.equal(malformed.outcomeUnknown, true);
const rules = SERIES_PRESETS.map((preset) => buildSeriesSplitPrompt(preset.id, 4));
assert.equal(new Set(rules).size, 4);
assert.match(rules[1], /不编造价格/);
assert.match(rules[2], /静态/);
assert.match(rules[3], /不合并为九宫格/);
const plan = Array.from({ length: 4 }, (_, index) => ({ title: `第 ${index + 1} 幕`, prompt: `小狐狸在场景 ${index + 1} 中行走` }));
assert.deepEqual(parseSeriesPlan(JSON.stringify(plan), 4), plan);
assert.throws(() => parseSeriesPlan(JSON.stringify(plan.slice(0, 3)), 4));
const scene = scenePrompt({ brief: '棕色短毛小狐狸在森林旅行', prompt: '沿着河边行走', index: 0, count: 4 });
assert.match(scene, /棕色短毛小狐狸在森林旅行/);
assert.match(scene, /沿着河边行走/);
assert.match(scene, /不生成拼版/);
console.log('generation contract, image validation and series planning passed');
