import assert from 'node:assert/strict';
import { validateGenerationSubmission, validateImageSize, generationRecipe, toImagesPayload } from '../shared/generation-contract.mjs';
import { buildSeriesSplitPrompt, parseSeriesPlan, scenePrompt, MAX_SERIES_BRIEF_LENGTH, MAX_SCENE_PROMPT_LENGTH } from '../shared/series-planning.mjs';
import { validateSubmissionImages } from '../server/generation-input.mjs';
import { imageInfo, normalizeImageResult } from '../server/image-result.mjs';
import { submissionHash } from '../server/state-store.mjs';
import { PNG, PNG_URL, MASK_URL, submission } from './fixtures.mjs';

const input = validateGenerationSubmission(submission('contract'));
assert.equal(toImagesPayload(input).n, 1);
assert.equal(toImagesPayload(input).quality, 'medium');
assert.equal(toImagesPayload(input).output_format, 'png');
assert.equal(Object.hasOwn(toImagesPayload(input), 'output_compression'), false);
for (const key of ['seed', 'cfg', 'cfg_scale', 'steps', 'num_inference_steps', 'weight', 'image_strength', 'reference_image_weight']) assert.throws(() => validateGenerationSubmission(submission(`invalid-${key}`, { [key]: 1 })), /不支持的字段/);
for (const size of ['1024x1024', '1280x720', '720x1280', '1024x768', '768x1024', '1536x1024', '1024x1536', '1344x576', '3840x2160', '2880x2880', 'auto']) assert.equal(validateImageSize(size), size);
for (const size of ['1x1', '1254x1254', '4096x4096', '1024x4000', 'wide']) assert.throws(() => validateImageSize(size));
assert.throws(() => validateGenerationSubmission(submission('bad-format', { outputFormat: 'jpeg', background: 'transparent' })), /透明背景/);
assert.throws(() => validateGenerationSubmission(submission('bad-quality', { quality: 'ultra' })), /质量/);
assert.throws(() => validateGenerationSubmission(submission('bad-mask', { mask: MASK_URL })), /需要参考图/);
assert.throws(() => validateGenerationSubmission(submission('refs', { references: Array(5).fill({ id: 'ref', name: 'ref', dataUrl: PNG_URL }) })), /最多/);
const edit = validateGenerationSubmission(submission('edit', { references: [{ id: 'ref', name: 'ref.png', dataUrl: PNG_URL }], mask: MASK_URL }));
const references = Array.from({ length: 4 }, (_, index) => ({ id: `ref-${index}`, name: `reference-${index + 1}.png`, dataUrl: PNG_URL }));
const multiReference = validateGenerationSubmission(submission('four-references', { references }));
assert.equal(multiReference.clientContext.mode, 'reference');
assert.deepEqual(toImagesPayload(multiReference).ref_images.map((ref) => ref.name), references.map((ref) => ref.name));
assert.deepEqual(generationRecipe(multiReference).references.map((ref) => ref.id), references.map((ref) => ref.id));
assert.throws(() => validateGenerationSubmission(submission('multiple-edit-originals', { references, mask: MASK_URL })), /只能使用一张原图/);
validateSubmissionImages(edit);
assert.equal(edit.clientContext.mode, 'edit');
assert.equal(generationRecipe(edit).hasMask, true);
assert.equal(JSON.stringify(generationRecipe(edit)).includes('base64'), false);
assert.deepEqual(imageInfo(PNG), { mime_type: 'image/png', width: 2, height: 2 });
assert.throws(() => validateSubmissionImages(submission('bad-image', { references: [{ id: 'ref', name: 'ref.png', dataUrl: 'data:image/png;base64,ZmFrZQ==' }] })), /损坏/);
assert.throws(() => validateSubmissionImages(submission('bad-mime', { references: [{ id: 'ref', name: 'ref.jpg', dataUrl: PNG_URL.replace('image/png', 'image/jpeg') }] })), /内容不一致/);
assert.notEqual(submissionHash(input), submissionHash({ ...input, referenceImage: { id: 'ref', name: 'ref.png', dataUrl: PNG_URL } }));
const anchored = { ...input, referenceJobId: 'original' };
assert.equal(submissionHash(anchored), submissionHash({ ...anchored, referenceImage: { id: 'ref', name: 'ref.png', dataUrl: PNG_URL } }));
const malformed = await normalizeImageResult({ ok: true, body: Buffer.from(JSON.stringify({ data: [{ b64_json: 'YmFk' }] })) });
assert.equal(malformed.ok, false);
assert.equal(malformed.outcomeUnknown, true);
for (const count of [3, 4, 8]) assert.match(buildSeriesSplitPrompt(count), new RegExp(`恰好 ${count} 项`));
for (const count of [0, 2, 9, 4.5, NaN, '4']) assert.throws(() => buildSeriesSplitPrompt(count), /分镜数量/);
const plan = Array.from({ length: 4 }, (_, index) => ({ title: `第 ${index + 1} 幕`, prompt: `小狐狸在场景 ${index + 1} 中行走` }));
assert.deepEqual(parseSeriesPlan(JSON.stringify(plan), 4), plan);
assert.throws(() => parseSeriesPlan(JSON.stringify(plan.slice(0, 3)), 4));
const literalPlan = plan.map((item) => ({ ...item, title: '标题: 保留信息', prompt: '图 1 的主体, 图 4 的背景.\n保留品牌 SproutCanvas, 文字 "第一行\n第二行", 占位符 {{name}}, 不添加价格.' }));
assert.deepEqual(parseSeriesPlan(JSON.stringify(literalPlan), 4), literalPlan);
assert.throws(() => parseSeriesPlan(JSON.stringify(plan.map((item) => ({ ...item, title: '长'.repeat(81) }))), 4), /标题/);
assert.throws(() => parseSeriesPlan(JSON.stringify(plan.map((item) => ({ ...item, prompt: '长'.repeat(MAX_SCENE_PROMPT_LENGTH + 1) }))), 4), /提示词/);
assert.throws(() => parseSeriesPlan(JSON.stringify(plan.map((item) => ({ ...item, prompt: '   ' }))), 4));
const scene = scenePrompt({ brief: '棕色短毛小狐狸在森林旅行', prompt: '沿着河边行走', index: 0, count: 4 });
assert.match(scene, /棕色短毛小狐狸在森林旅行/);
assert.match(scene, /沿着河边行走/);
assert.match(scene, /不生成拼版/);
const largestScene = scenePrompt({ brief: '需'.repeat(MAX_SERIES_BRIEF_LENGTH), prompt: '画'.repeat(MAX_SCENE_PROMPT_LENGTH), index: 7, count: 8, referenceCount: 4, hasContinuityReference: true });
assert.ok(largestScene.length <= 24000, 'accepted planning text fits the generation request limit');
const series = validateGenerationSubmission({ ...submission('free-series'), clientContext: { ...input.clientContext, kind: 'series', seriesId: 'series', sceneId: 'scene' } });
assert.equal(series.clientContext.template, undefined);
console.log('generation contract, image validation and series planning passed');
